version: '3'
services:
  signage:
    build: .
    image: trabzon-signage
    container_name: trabzon-signage
    restart: unless-stopped
    ports:
      - "8088:5000"  # Dışarıya 80 portundan açılır
    volumes:
      - ./server/data:/app/data  # Veriler silinmesin diye dışarı mount et
    environment:
      - NODE_ENV=production
      - TZ=Europe/Istanbul